### ISSUE TITLE
[enchancement] allow whitespaces in time string

### ISSUE THREAD

**Issue by Valian** [rdev-hackaton/GitHubTimeTracker#33]
Currently this is wrong because of space between hours and minutes:

```
:clock1: 1h 12m
```

Fix regex to allow such notation

**Comment by ffigiel** [comment]
Shouldn't we keep the time string format as concise as possible? That was the motivation behind such restricted format. Guys?

**Comment by ffigiel** [comment]
By the way, we should probably drop the support for days (the `1d` part), right? This doesn't make much sense

**Comment by ffigiel** [comment]
Once we decide on that, let's mention the time entry syntax in the readme
